# Default values for helm-common-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace settings
namespace:
  create: true
  name: default

# Container definitions - can have multiple containers
containers:
  - name: main
    image:
      repository: nginx
      tag: ""
      pullPolicy: IfNotPresent
    env: []
    # Example:
    # - name: EXAMPLE_ENV
    #   valueFrom:
    #     secretKeyRef:
    #       name: my-secret
    #       key: my-key

# Image pull secrets for private registries
imagePullSecrets: []

# Service account settings
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security context settings
podSecurityContext: {}
securityContext: {}

# Service settings
service:
  enabled: true
  type: ClusterIP
  port: 80

# Ingress settings
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# Resource requests and limits
resources: {}

# Liveness and readiness probes
livenessProbe: {}
readinessProbe: {}

# Autoscaling settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Volume settings
volumes: []
volumeMounts: []

# Node selector, tolerations, and affinity
nodeSelector: {}
tolerations: []
affinity: {}

# Config file settings
configFiles:
  # Example:
  # - name: my-config
  #   mountPath: /etc/config/my-config.yaml
  #   data:
  #     key1: value1
  #     key2: value2
